analyzer:
  exclude:
    - build/**
  errors:
    unused_import: warning
    dead_code: warning

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
